services:
  db:
    image: postgres:16-alpine
    container_name: cheezious_postgres
    restart: always
    environment:
      POSTGRES_USER: cheezious
      POSTGRES_PASSWORD: cheezious_secret
      POSTGRES_DB: cheezious_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cheezious -d cheezious_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
