import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';
import assert from 'node:assert/strict';
import bcrypt from 'bcryptjs';
const db = new PrismaClient();
const base = 'http://127.0.0.1:5000/api/v1';
const slug = `verify-${randomUUID()}`;
let tenantId: string | undefined;
async function request(path: string, token?: string, method = 'GET', body?: any) {
  const res = await fetch(base + path, { method, headers: { 'Content-Type':'application/json', 'x-tenant-slug':slug, ...(token ? {Authorization:`Bearer ${token}`} : {}) }, body: body ? JSON.stringify(body) : undefined });
  return {status:res.status,json:await res.json() as any};
}
async function main() {
  try {
    const tenant = await db.tenant.create({data:{slug,name:'Temporary verification restaurant',branding:{create:{logo:''}},settings:{create:{minimumOrder:0,deliveryFee:100,freeDeliveryThreshold:2000,taxEnabled:true,taxRate:10}}}});
    tenantId=tenant.id;
    const branch=await db.branch.create({data:{tenantId,name:'Test branch',city:'Test',address:'Test address',phone:'0000000000',minimumOrder:0,deliveryFee:100}});
    const password=await bcrypt.hash('TemporaryPassword123',10);
    const users:any={}; const sessions:any={};
    for (const role of ['TENANT_ADMIN','CUSTOMER','RIDER','KITCHEN_STAFF','SUPPORT_STAFF'] as const) {
      const email=`${role.toLowerCase()}-${slug}@example.test`;
      const user=await db.user.create({data:{tenantId,role,email,name:role,password}});
      if(role==='RIDER') users.rider=await db.rider.create({data:{tenantId,userId:user.id}});
      if(role==='KITCHEN_STAFF' || role==='SUPPORT_STAFF') await db.branchStaff.create({data:{userId:user.id,branchId:branch.id,role}});
      const login=await request('/auth/login',undefined,'POST',{email,password:'TemporaryPassword123'});
      assert.equal(login.status,200,JSON.stringify(login.json)); users[role]=login.json.data.token; sessions[role]=login.json.data;
    }
    const product=await db.product.create({data:{tenantId,name:'Test meal',slug:'meal',basePrice:500,image:'',optionGroups:{create:{tenantId,name:'Size',minSelect:1,maxSelect:1,isRequired:true,options:{create:{name:'Large',priceModifier:100}}}}},include:{optionGroups:{include:{options:true}}}});
    await db.voucher.create({data:{tenantId,code:'TEN',discountType:'PERCENT',discountValue:10,minimumOrder:0}});
    const payload={branchId:branch.id,orderMode:'DELIVERY',voucherCode:'TEN',items:[{productId:product.id,quantity:2,optionIds:[product.optionGroups[0].options[0].id]}]};
    assert.equal((await request('/orders')).status,401);
    const quote=await request('/orders/quote',users.CUSTOMER,'POST',payload);
    assert.equal(quote.status,200,JSON.stringify(quote.json)); assert.equal(quote.json.data.total,1288);
    const placed=await request('/orders',users.CUSTOMER,'POST',{...payload,customerName:'Verification customer',customerPhone:'0000000000',deliveryAddress:'Test only',paymentMethod:'COD',total:1});
    assert.equal(placed.status,201,JSON.stringify(placed.json)); assert.equal(placed.json.data.total,1288);
    const id=placed.json.data.id;
    const saved=await db.order.findUniqueOrThrow({where:{id},include:{items:true}});
    assert.match(saved.items[0].optionsJson!,/Large/);
    assert.equal((await request(`/orders/${id}/status`,users.CUSTOMER,'PATCH',{status:'DELIVERED'})).status,403);
    for(const status of ['PREPARING','READY']) assert.equal((await request(`/orders/${id}/status`,users.KITCHEN_STAFF,'PATCH',{status})).status,200);
    const assigned=await request('/deliveries/assign',users.TENANT_ADMIN,'POST',{orderId:id,riderId:users.rider.id});
    assert.equal(assigned.status,200,JSON.stringify(assigned.json)); const deliveryId=assigned.json.data.id;
    assert.equal((await request('/deliveries/assigned',users.RIDER)).json.data.length,1);
    for(const status of ['ACCEPTED','PICKED_UP','ON_THE_WAY']) assert.equal((await request(`/deliveries/${deliveryId}/status`,users.RIDER,'PATCH',{status})).status,200);
    assert.equal((await request(`/deliveries/${deliveryId}/location`,users.RIDER,'POST',{latitude:33.68,longitude:73.04})).status,200);
    assert.equal((await request(`/deliveries/${deliveryId}/location`,users.CUSTOMER,'POST',{latitude:33.68,longitude:73.04})).status,403);
    const codBefore=await db.codRecord.findUniqueOrThrow({where:{orderId:id}}); assert.equal(codBefore.expectedAmount,1288); assert.equal(codBefore.status,'PENDING_COLLECTION');
    assert.equal((await request(`/deliveries/${deliveryId}/status`,users.RIDER,'PATCH',{status:'DELIVERED'})).status,409);
    assert.equal((await request(`/payments/cod/${id}/collect`,users.CUSTOMER,'POST',{amount:1288})).status,403);
    const collected=await request(`/payments/cod/${id}/collect`,users.RIDER,'POST',{amount:1288}); assert.equal(collected.status,200,JSON.stringify(collected.json)); assert.equal(collected.json.data.status,'COLLECTED_BY_RIDER');
    assert.equal((await request(`/payments/cod/${id}/collect`,users.RIDER,'POST',{amount:1288})).status,409);
    assert.equal((await request(`/payments/cod/${id}/settlement`,users.SUPPORT_STAFF,'PATCH',{status:'SETTLED',receivedAmount:1288})).status,403);
    assert.equal((await request(`/payments/cod/${id}/settlement`,users.TENANT_ADMIN,'PATCH',{status:'PENDING_SETTLEMENT',receivedAmount:1288})).status,200);
    const settled=await request(`/payments/cod/${id}/settlement`,users.TENANT_ADMIN,'PATCH',{status:'SETTLED',receivedAmount:1288}); assert.equal(settled.status,200,JSON.stringify(settled.json)); assert.equal(settled.json.data.differenceAmount,0);
    assert.equal((await request(`/orders/${id}/messages`,users.CUSTOMER,'POST',{message:'Please call when outside.'})).status,201);
    assert.equal((await request(`/orders/${id}/messages`,users.RIDER,'POST',{message:'I am nearby.'})).status,201);
    const chat=await request(`/orders/${id}/messages`,users.CUSTOMER); assert.equal(chat.status,200); assert.ok(chat.json.data.some((message:any)=>message.message==='I am nearby.'));
    assert.equal((await request(`/orders/${id}/internal-notes`,users.CUSTOMER)).status,403);
    assert.equal((await request(`/orders/${id}/internal-notes`,users.TENANT_ADMIN,'POST',{note:'Customer confirmed replacement.'})).status,201);
    assert.equal((await request(`/deliveries/${deliveryId}/status`,users.RIDER,'PATCH',{status:'DELIVERED'})).status,200);
    assert.equal((await request(`/orders/${id}/messages`,users.RIDER)).status,404);
    const finished=await request(`/orders/${id}`,users.CUSTOMER);
    assert.equal(finished.json.data.status,'DELIVERED'); assert.equal(finished.json.data.delivery.status,'DELIVERED'); assert.equal(finished.json.data.statusHistory.length,7);
    assert.equal(JSON.stringify(finished.json).includes('password'),false);
    assert.equal((await request(`/orders/admin/${id}`,users.CUSTOMER)).status,403);
    const adminDetail=await request(`/orders/admin/${id}`,users.TENANT_ADMIN);
    assert.equal(adminDetail.status,200,JSON.stringify(adminDetail.json));
    assert.equal(adminDetail.json.data.financial.total,1288); assert.ok(adminDetail.json.data.kitchen.preparationDurationMs >= 0);
    assert.ok(adminDetail.json.data.timeline.some((event:any)=>event.actor?.name==='KITCHEN_STAFF'));
    const outsider=await db.user.create({data:{tenantId,name:'Other customer',email:`other-${slug}@example.test`,password,role:'CUSTOMER'}});
    const other=await request('/auth/login',undefined,'POST',{email:outsider.email,password:'TemporaryPassword123'});
    assert.equal((await request(`/orders/${id}`,other.json.data.token)).status,404);
    assert.equal((await request('/orders',other.json.data.token)).json.data.length,0);
    assert.equal((await request(`/orders/${id}/messages`,other.json.data.token)).status,404);
    const cross=await fetch(base+'/orders',{headers:{'x-tenant-slug':'cheezious',Authorization:`Bearer ${users.CUSTOMER}`}});
    assert.equal(cross.status,403);
    const refreshed=await request('/auth/refresh',undefined,'POST',{refreshToken:sessions.TENANT_ADMIN.refreshToken});
    assert.equal(refreshed.status,200,JSON.stringify(refreshed.json));
    assert.notEqual(refreshed.json.data.refreshToken,sessions.TENANT_ADMIN.refreshToken);
    assert.equal((await request('/auth/refresh',undefined,'POST',{refreshToken:sessions.TENANT_ADMIN.refreshToken})).status,401);
    assert.equal((await request('/auth/logout',undefined,'POST',{refreshToken:refreshed.json.data.refreshToken})).status,200);
    assert.equal((await request('/auth/refresh',undefined,'POST',{refreshToken:refreshed.json.data.refreshToken})).status,401);
    const invited=await request('/staff',users.TENANT_ADMIN,'POST',{name:'Invited kitchen employee',email:`invited-${slug}@example.test`,role:'KITCHEN_STAFF',branchIds:[branch.id],employeeId:'VERIFY-1'});
    assert.equal(invited.status,201,JSON.stringify(invited.json));
    const invitationPath=invited.json.data.developmentInvitationPath as string;
    assert.ok(invitationPath);
    const invitationToken=new URL(`http://local${invitationPath}`).searchParams.get('token');
    assert.equal((await request('/staff/accept-invitation',undefined,'POST',{token:invitationToken,password:'InvitedPassword123'})).status,200);
    const staffLogin=await request('/auth/login',undefined,'POST',{email:`invited-${slug}@example.test`,password:'InvitedPassword123'});
    assert.equal(staffLogin.status,200,JSON.stringify(staffLogin.json));
    assert.ok(staffLogin.json.data.user.roles.includes('KITCHEN_STAFF'));
    const staffList=await request('/staff',users.TENANT_ADMIN);
    assert.equal(staffList.status,200); assert.ok(staffList.json.data.some((member:any)=>member.id===invited.json.data.id));
    const changed=await request(`/staff/${invited.json.data.id}`,users.TENANT_ADMIN,'PATCH',{role:'KITCHEN_MANAGER',branchIds:[branch.id]});
    assert.equal(changed.status,200,JSON.stringify(changed.json));
    assert.equal((await request(`/staff/${invited.json.data.id}/status`,users.TENANT_ADMIN,'PATCH',{isActive:false})).status,200);
    assert.equal((await request('/auth/login',undefined,'POST',{email:`invited-${slug}@example.test`,password:'InvitedPassword123'})).status,401);
    assert.ok(await db.auditLog.findFirst({where:{tenantId,entityId:invited.json.data.id,action:'STAFF_DISABLED'}}));
    const riderUpdated=await request(`/deliveries/riders/${users.rider.id}`,users.TENANT_ADMIN,'PATCH',{branchId:branch.id,vehicleType:'TEST BIKE',vehicleNumber:'VERIFY-42',deliveryZone:'Verification zone'});
    assert.equal(riderUpdated.status,200,JSON.stringify(riderUpdated.json)); assert.equal(riderUpdated.json.data.deliveryZone,'Verification zone');
    const riderProfile=await request(`/deliveries/riders/${users.rider.id}`,users.TENANT_ADMIN);
    assert.equal(riderProfile.status,200); assert.ok(riderProfile.json.data.deliveries.length); assert.ok(riderProfile.json.data.activity.length);
    assert.ok(await db.auditLog.findFirst({where:{tenantId,entityId:codBefore.id,action:'COD_COLLECTED'}}));
    assert.ok(await db.auditLog.findFirst({where:{tenantId,entityId:codBefore.id,action:'COD_SETTLEMENT_CHANGED'}}));
    assert.equal((await request(`/branches/${branch.id}/toggle`,users.TENANT_ADMIN,'PATCH')).status,200);
    assert.equal((await request(`/products/${product.id}`,users.TENANT_ADMIN,'PUT',{basePrice:525})).status,200);
    assert.equal((await request('/vouchers',users.TENANT_ADMIN,'POST',{code:'AUDIT',discountType:'FIXED',discountValue:25,minimumOrder:0})).status,201);
    assert.equal((await request(`/tenants/${tenantId}/settings`,users.TENANT_ADMIN,'PUT',{deliveryFee:125})).status,200);
    assert.equal((await request('/audit',users.CUSTOMER)).status,403);
    assert.equal((await request('/audit',users.SUPPORT_STAFF)).status,403);
    const audit=await request(`/audit?action=COD&branchId=${branch.id}`,users.TENANT_ADMIN); assert.equal(audit.status,200,JSON.stringify(audit.json)); assert.ok(audit.json.data.records.length>=2); assert.ok(audit.json.data.records.every((entry:any)=>entry.branchId===branch.id && entry.actorRole));
    const adminAudits=await request('/audit?limit=200',users.TENANT_ADMIN); assert.equal(adminAudits.status,200); for(const action of ['BRANCH_CLOSED','PRODUCT_PRICE_CHANGED','VOUCHER_CREATED','SETTINGS_CHANGED']) assert.ok(adminAudits.json.data.records.some((entry:any)=>entry.action===action),action);
    console.log('PASS: database-backed ordering, isolation, sessions, operations, COD, and filtered audit authorization/coverage.');
  } finally {
    if(tenantId) { await db.auditLog.deleteMany({where:{tenantId}}); await db.tenant.delete({where:{id:tenantId}}); console.log('Temporary verification tenant removed.'); }
    await db.$disconnect();
  }
}
main().catch(error=>{console.error(error);process.exitCode=1;});
